spring:
  application:
    name: kafka.integration
  cloud:
    stream:
      bindings:
        ai-producer:
          destination: learning-ai
          producer:
            useNativeEncoding: true
        rag-producer:
          destination: rag-events
          producer:
            useNativeEncoding: true
      kafka:
        binder:
          producerProperties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
          brokers: localhost:9092
search:
  api:
    base-url: localhost:8000
server:
  port: 8090
file:
  watcher:
    directory: ./files
    chunk-size: 1000
    chunk-overlap: 4i00
    retry:
      max-attempts: 3
      delay-seconds: 5
    pinecone:
      index-name: infra-knowledge
      namespace: file-data
    metadata:
      language: en
      tags: ["knowledge","learning"]